import { NextRequest, NextResponse } from 'next/server'
import ExcelJS from 'exceljs'
import { isAuthenticated } from '@/lib/session/session'
import type { MatrixRow, ProcessEntry } from '@/modules/csr/types'

/* ─── Styling constants ─────────────────────────────────────────── */

const BLUE = 'FF1D4ED8'
const WHITE = 'FFFFFFFF'
const LIGHT_BLUE = 'FFDBEAFE'
const RED_BG = 'FFFEE2E2'
const ORANGE_BG = 'FFFFEDD5'
const YELLOW_BG = 'FFFEF9C3'
const GREEN_BG = 'FFDCFCE7'
const GRAY_BG = 'FFF8FAFC'

const thinBorder: Partial<ExcelJS.Borders> = {
  top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
  bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
  left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
  right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
}

function fill(color: string): ExcelJS.Fill {
  return { type: 'pattern', pattern: 'solid', fgColor: { argb: color } }
}

/* ─── Request schema ────────────────────────────────────────────── */

interface ExportRequest {
  matrixRows: MatrixRow[]
  processes: ProcessEntry[]
  selectedOems: string[]
  companyName?: string
  companyLocation?: string
  language: 'de' | 'en'
}

/* ─── Labels ────────────────────────────────────────────────────── */

const LABELS = {
  en: {
    sheetName: 'CSR Matrix',
    title: 'Customer-Specific Requirements Matrix',
    generated: 'Generated',
    company: 'Company',
    location: 'Location',
    oems: 'OEMs',
    totalReqs: 'Total Requirements',
    chapter: 'IATF Chapter',
    reqTitle: 'Requirement',
    oem: 'OEM / Source',
    description: 'Description',
    version: 'Version',
    change: 'Change Status',
    risk: 'Risk',
    processHeader: 'Affected Processes',
    legend: 'Legend',
    legendBase: 'IATF 16949 = Base standard requirement',
    legendOem: 'OEM column = Customer-specific requirement on top of IATF',
    legendX: 'x = Process is affected by this requirement',
    legendRisk: 'Risk: critical / high / medium / low',
    riskCritical: 'Critical',
    riskHigh: 'High',
    riskMedium: 'Medium',
    riskLow: 'Low',
    new: 'New',
    updated: 'Updated',
    unchanged: 'Unchanged',
    deleted: 'Deleted',
    disclaimer: 'This matrix was generated by IATF Solutions CSR Matrix Tool. It is based on publicly available IATF 16949 and OEM CSR requirements. Always verify against the latest OEM source documents.',
  },
  de: {
    sheetName: 'CSR Matrix',
    title: 'Kundenspezifische Anforderungsmatrix',
    generated: 'Erstellt am',
    company: 'Unternehmen',
    location: 'Standort',
    oems: 'OEMs',
    totalReqs: 'Anforderungen gesamt',
    chapter: 'IATF Kapitel',
    reqTitle: 'Anforderung',
    oem: 'OEM / Quelle',
    description: 'Beschreibung',
    version: 'Version',
    change: 'Änderungsstatus',
    risk: 'Risiko',
    processHeader: 'Betroffene Prozesse',
    legend: 'Legende',
    legendBase: 'IATF 16949 = Grundanforderung des Standards',
    legendOem: 'OEM-Spalte = Kundenspezifische Anforderung über IATF hinaus',
    legendX: 'x = Prozess ist von dieser Anforderung betroffen',
    legendRisk: 'Risiko: kritisch / hoch / mittel / niedrig',
    riskCritical: 'Kritisch',
    riskHigh: 'Hoch',
    riskMedium: 'Mittel',
    riskLow: 'Niedrig',
    new: 'Neu',
    updated: 'Aktualisiert',
    unchanged: 'Unverändert',
    deleted: 'Entfernt',
    disclaimer: 'Diese Matrix wurde mit dem IATF Solutions CSR Matrix Tool erstellt. Sie basiert auf öffentlich verfügbaren IATF 16949 und OEM CSR-Anforderungen. Bitte stets mit den aktuellen OEM-Quelldokumenten abgleichen.',
  },
} as const

/* ─── Route handler ─────────────────────────────────────────────── */

export async function POST(request: NextRequest) {
  // Auth check
  const authed = await isAuthenticated()
  if (!authed) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  let body: ExportRequest
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const { matrixRows, processes, selectedOems, companyName, companyLocation, language } = body

  if (!matrixRows || !Array.isArray(matrixRows) || matrixRows.length === 0) {
    return NextResponse.json({ error: 'No matrix data' }, { status: 400 })
  }

  const L = LABELS[language] ?? LABELS.en

  try {
    const wb = new ExcelJS.Workbook()
    wb.creator = 'IATF Solutions'
    wb.created = new Date()

    const ws = wb.addWorksheet(L.sheetName)

    // Fixed columns: Chapter, Title, OEM, Description, Version, Change, Risk
    const fixedCols = 7
    const processCols = processes.length
    const totalCols = fixedCols + processCols

    // Column widths
    const columns: Partial<ExcelJS.Column>[] = [
      { width: 14 },  // Chapter
      { width: 28 },  // Title
      { width: 16 },  // OEM
      { width: 50 },  // Description
      { width: 14 },  // Version
      { width: 12 },  // Change
      { width: 10 },  // Risk
    ]
    for (let i = 0; i < processCols; i++) {
      columns.push({ width: 6 })
    }
    ws.columns = columns

    let row = 1

    // ───── Title block ─────
    ws.mergeCells(row, 1, row, totalCols)
    const titleCell = ws.getCell(row, 1)
    titleCell.value = L.title
    titleCell.font = { bold: true, size: 14, color: { argb: WHITE } }
    titleCell.fill = fill(BLUE)
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' }
    ws.getRow(row).height = 32
    row++

    // Metadata rows
    const metaItems: [string, string][] = [
      [L.generated, new Date().toLocaleDateString(language === 'de' ? 'de-DE' : 'en-GB')],
      [L.company, companyName || '—'],
      [L.location, companyLocation || '—'],
      [L.oems, selectedOems.join(', ')],
      [L.totalReqs, String(matrixRows.length)],
    ]
    for (const [label, val] of metaItems) {
      ws.mergeCells(row, 2, row, totalCols)
      ws.getCell(row, 1).value = label
      ws.getCell(row, 1).font = { bold: true, size: 9, color: { argb: 'FF475569' } }
      ws.getCell(row, 2).value = val
      ws.getCell(row, 2).font = { size: 9 }
      row++
    }

    row++ // blank separator

    // ───── Header row ─────
    const headers = [
      L.chapter, L.reqTitle, L.oem, L.description, L.version, L.change, L.risk,
      ...processes.map((p) => p.name),
    ]

    // Process names as rotated headers
    const headerRow = ws.getRow(row)
    headerRow.height = processCols > 0 ? 80 : 24
    for (let c = 0; c < headers.length; c++) {
      const cell = ws.getCell(row, c + 1)
      cell.value = headers[c]
      cell.font = { bold: true, size: 9, color: { argb: WHITE } }
      cell.fill = fill(BLUE)
      cell.border = thinBorder
      cell.alignment = {
        horizontal: 'center',
        vertical: 'bottom',
        wrapText: true,
        textRotation: c >= fixedCols ? 90 : 0,
      }
    }
    row++

    // ───── Data rows ─────
    const processIdSet = new Set<string>()
    for (const r of matrixRows) {
      for (const pid of r.affectedProcessIds) {
        processIdSet.add(pid)
      }
    }

    // Sort: by chapter number
    const sorted = [...matrixRows].sort((a, b) =>
      a.iatfChapter.localeCompare(b.iatfChapter, undefined, { numeric: true }),
    )

    for (let i = 0; i < sorted.length; i++) {
      const mr = sorted[i]
      const isAlt = i % 2 === 1
      const bgColor = isAlt ? GRAY_BG : undefined

      const riskBg =
        mr.risk === 'critical' ? RED_BG
        : mr.risk === 'high' ? ORANGE_BG
        : mr.risk === 'medium' ? YELLOW_BG
        : GREEN_BG

      const riskLabel =
        mr.risk === 'critical' ? L.riskCritical
        : mr.risk === 'high' ? L.riskHigh
        : mr.risk === 'medium' ? L.riskMedium
        : L.riskLow

      const changeLabel =
        mr.changeStatus === 'new' ? L.new
        : mr.changeStatus === 'updated' ? L.updated
        : mr.changeStatus === 'deleted' ? L.deleted
        : L.unchanged

      const values: (string | number)[] = [
        mr.iatfChapter,
        mr.title,
        mr.oem,
        mr.text,
        mr.version,
        changeLabel,
        riskLabel,
      ]

      // Process X-marks
      for (const p of processes) {
        values.push(mr.affectedProcessIds.includes(p.id) ? 'x' : '')
      }

      for (let c = 0; c < values.length; c++) {
        const cell = ws.getCell(row, c + 1)
        cell.value = values[c]
        cell.font = { size: 8 }
        cell.border = thinBorder
        cell.alignment = {
          vertical: 'top',
          wrapText: c === 3, // wrap description
          horizontal: c >= fixedCols ? 'center' : 'left',
        }

        if (c === 6) {
          // Risk column colour
          cell.fill = fill(riskBg)
        } else if (bgColor) {
          cell.fill = fill(bgColor)
        }

        // X-mark styling
        if (c >= fixedCols && values[c] === 'x') {
          cell.font = { bold: true, size: 9, color: { argb: BLUE } }
          cell.fill = fill(LIGHT_BLUE)
        }
      }

      // Auto row height for description
      const descLen = (mr.text || '').length
      const lines = Math.max(1, Math.ceil(descLen / 70))
      ws.getRow(row).height = Math.max(15, lines * 13)
      row++
    }

    row++ // blank

    // ───── Legend ─────
    ws.mergeCells(row, 1, row, totalCols)
    ws.getCell(row, 1).value = L.legend
    ws.getCell(row, 1).font = { bold: true, size: 10, color: { argb: WHITE } }
    ws.getCell(row, 1).fill = fill(BLUE)
    row++

    const legendItems = [L.legendBase, L.legendOem, L.legendX, L.legendRisk]
    for (const item of legendItems) {
      ws.mergeCells(row, 1, row, totalCols)
      ws.getCell(row, 1).value = item
      ws.getCell(row, 1).font = { size: 8, italic: true }
      row++
    }

    row++

    // ───── Disclaimer ─────
    ws.mergeCells(row, 1, row, totalCols)
    ws.getCell(row, 1).value = L.disclaimer
    ws.getCell(row, 1).font = { size: 7, italic: true, color: { argb: 'FF94A3B8' } }
    ws.getCell(row, 1).alignment = { wrapText: true }

    // ───── Generate buffer ─────
    const buffer = await wb.xlsx.writeBuffer()

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="CSR_Matrix.xlsx"`,
        'Cache-Control': 'no-store',
      },
    })
  } catch (err) {
    console.error('[CSR Export] Excel generation failed:', err)
    return NextResponse.json({ error: 'Excel generation failed' }, { status: 500 })
  }
}
